apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "eksbcp"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "eksbcp"
    spec:
      containers:
        - name: "eksbcp"
          image: "testbcpacr.azurecr.io/eksbcp"
          ports:
          - containerPort: 80