apiVersion: v1
kind: Service
metadata:
    name: "eksbcp"
    labels:
        app: "eksbcp"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "eksbcp"